# Classification Exercise

We'll be working with some California Census Data, we'll be trying to use various features of an individual to predict what class of income they belogn in (>50k or <=50k). 

Here is some information about the data:

<table>
<thead>
<tr>
<th>Column Name</th>
<th>Type</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr>
<td>age</td>
<td>Continuous</td>
<td>The age of the individual</td>
</tr>
<tr>
<td>workclass</td>
<td>Categorical</td>
<td>The type of employer the  individual has (government,  military, private, etc.).</td>
</tr>
<tr>
<td>fnlwgt</td>
<td>Continuous</td>
<td>The number of people the census  takers believe that observation  represents (sample weight). This  variable will not be used.</td>
</tr>
<tr>
<td>education</td>
<td>Categorical</td>
<td>The highest level of education  achieved for that individual.</td>
</tr>
<tr>
<td>education_num</td>
<td>Continuous</td>
<td>The highest level of education in  numerical form.</td>
</tr>
<tr>
<td>marital_status</td>
<td>Categorical</td>
<td>Marital status of the individual.</td>
</tr>
<tr>
<td>occupation</td>
<td>Categorical</td>
<td>The occupation of the individual.</td>
</tr>
<tr>
<td>relationship</td>
<td>Categorical</td>
<td>Wife, Own-child, Husband,  Not-in-family, Other-relative,  Unmarried.</td>
</tr>
<tr>
<td>race</td>
<td>Categorical</td>
<td>White, Asian-Pac-Islander,  Amer-Indian-Eskimo, Other, Black.</td>
</tr>
<tr>
<td>gender</td>
<td>Categorical</td>
<td>Female, Male.</td>
</tr>
<tr>
<td>capital_gain</td>
<td>Continuous</td>
<td>Capital gains recorded.</td>
</tr>
<tr>
<td>capital_loss</td>
<td>Continuous</td>
<td>Capital Losses recorded.</td>
</tr>
<tr>
<td>hours_per_week</td>
<td>Continuous</td>
<td>Hours worked per week.</td>
</tr>
<tr>
<td>native_country</td>
<td>Categorical</td>
<td>Country of origin of the  individual.</td>
</tr>
<tr>
<td>income</td>
<td>Categorical</td>
<td>"&gt;50K" or "&lt;=50K", meaning  whether the person makes more  than \$50,000 annually.</td>
</tr>
</tbody>
</table>

## Follow the Directions in Bold. If you get stuck, check out the solutions lecture.

### THE DATA

** Read in the census_data.csv data with pandas**

In [1]:
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
my_data = pd.read_csv("/Users/mohamedali/Desktop/Python-DS-ML/Tensorflow/Tensorflow-Bootcamp-master/02-TensorFlow-Basics/census_data.csv")

In [3]:
my_data

,age,workclass,education,education_num,marital_status,occupation,relationship,race,gender,capital_gain,capital_loss,hours_per_week,native_country,income_bracket
0,39,State-gov,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
5,37,Private,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
6,49,Private,9th,5,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0,0,16,Jamaica,<=50K
7,52,Self-emp-not-inc,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
8,31,Private,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
9,42,Private,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178,0,40,United-States,>50K
10,37,Private,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,80,United-States,>50K
11,30,State-gov,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,40,India,>50K
12,23,Private,Bachelors,13,Never-married,Adm-clerical,Own-child,White,Female,0,0,30,United-States,<=50K
13,32,Private,Assoc-acdm,12,Never-married,Sales,Not-in-family,Black,Male,0,0,50,United-States,<=50K
14,40,Private,Assoc-voc,11,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,0,0,40,?,>50K
15,34,Private,7th-8th,4,Married-civ-spouse,Transport-moving,Husband,Amer-Indian-Eskimo,Male,0,0,45,Mexico,<=50K
16,25,Self-emp-not-inc,HS-grad,9,Never-married,Farming-fishing,Own-child,White,Male,0,0,35,United-States,<=50K
17,32,Private,HS-grad,9,Never-married,Machine-op-inspct,Unmarried,White,Male,0,0,40,United-States,<=50K
18,38,Private,11th,7,Married-civ-spouse,Sales,Husband,White,Male,0,0,50,United-States,<=50K
19,43,Self-emp-not-inc,Masters,14,Divorced,Exec-managerial,Unmarried,White,Female,0,0,45,United-States,>50K
20,40,Private,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
21,54,Private,HS-grad,9,Separated,Other-service,Unmarried,Black,Female,0,0,20,United-States,<=50K
22,35,Federal-gov,9th,5,Married-civ-spouse,Farming-fishing,Husband,Black,Male,0,0,40,United-States,<=50K
23,43,Private,11th,7,Married-civ-spouse,Transport-moving,Husband,White,Male,0,2042,40,United-States,<=50K
24,59,Private,HS-grad,9,Divorced,Tech-support,Unmarried,White,Female,0,0,40,United-States,<=50K
25,56,Local-gov,Bachelors,13,Married-civ-spouse,Tech-support,Husband,White,Male,0,0,40,United-States,>50K
26,19,Private,HS-grad,9,Never-married,Craft-repair,Own-child,White,Male,0,0,40,United-States,<=50K
27,54,?,Some-college,10,Married-civ-spouse,?,Husband,Asian-Pac-Islander,Male,0,0,60,South,>50K
28,39,Private,HS-grad,9,Divorced,Exec-managerial,Not-in-family,White,Male,0,0,80,United-States,<=50K
29,49,Private,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32531,30,?,Bachelors,13,Never-married,?,Not-in-family,Asian-Pac-Islander,Female,0,0,99,United-States,<=50K
32532,34,Private,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
32533,54,Private,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,Asian-Pac-Islander,Male,0,0,50,Japan,>50K
32534,37,Private,Some-college,10,Divorced,Adm-clerical,Unmarried,White,Female,0,0,39,United-States,<=50K
32535,22,Private,12th,8,Never-married,Protective-serv,Own-child,Black,Male,0,0,35,United-States,<=50K
32536,34,Private,Bachelors,13,Never-married,Exec-managerial,Not-in-family,White,Female,0,0,55,United-States,>50K
32537,30,Private,HS-grad,9,Never-married,Craft-repair,Not-in-family,Black,Male,0,0,46,United-States,<=50K
32538,38,Private,Bachelors,13,Divorced,Prof-specialty,Unmarried,Black,Female,15020,0,45,United-States,>50K
32539,71,?,Doctorate,16,Married-civ-spouse,?,Husband,White,Male,0,0,10,United-States,>50K
32540,45,State-gov,HS-grad,9,Separated,Adm-clerical,Own-child,White,Female,0,0,40,United-States,<=50K
32541,41,?,HS-grad,9,Separated,?,Not-in-family,Black,Female,0,0,32,United-States,<=50K
32542,72,?,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,0,0,25,United-States,<=50K
32543,45,Local-gov,Assoc-acdm,12,Divorced,Prof-specialty,Unmarried,White,Female,0,0,48,United-States,<=50K
32544,31,Private,Masters,14,Divorced,Other-service,Not-in-family,Other,Female,0,0,30,United-States,<=50K
32545,39,Local-gov,Assoc-acdm,12,Married-civ-spouse,Adm-clerical,Wife,White,Female,0,0,20,United-States,>50K
32546,37,Private,Assoc-acdm,12,Divorced,Tech-support,Not-in-family,White,Female,0,0,40,United-States,<=50K
32547,43,Private,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,Mexico,<=50K
32548,65,Self-emp-not-inc,Prof-school,15,Never-married,Prof-specialty,Not-in-family,White,Male,1086,0,60,United-States,<=50K
32549,43,State-gov,Some-college,10,Divorced,Adm-clerical,Other-relative,White,Female,0,0,40,United-States,<=50K
32550,43,Self-emp-not-inc,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,50,United-States,<=50K
32551,32,Private,10th,6,Married-civ-spouse,Handlers-cleaners,Husband,Amer-Indian-Eskimo,Male,0,0,40,United-States,<=50K
32552,43,Private,Assoc-voc,11,Married-civ-spouse,Sales,Husband,White,Male,0,0,45,United-States,<=50K
32553,32,Private,Masters,14,Never-married,Tech-support,Not-in-family,Asian-Pac-Islander,Male,0,0,11,Taiwan,<=50K
32554,53,Private,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K
32555,22,Private,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,<=50K
32556,27,Private,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

** TensorFlow won't be able to understand strings as labels, you'll need to use pandas .apply() method to apply a custom function that converts them to 0s and 1s. This might be hard if you aren't very familiar with pandas, so feel free to take a peek at the solutions for this part.**

** Convert the Label column to 0s and 1s instead of strings.**

In [4]:
def convert_label(label):
    if label == '<=50K':
        return 0
    else:
        return 1

In [5]:
my_data['income_bracket'] = my_data['income_bracket'].apply(convert_label)

In [6]:
my_data

,age,workclass,education,education_num,marital_status,occupation,relationship,race,gender,capital_gain,capital_loss,hours_per_week,native_country,income_bracket
0,39,State-gov,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,1
1,50,Self-emp-not-inc,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,1
2,38,Private,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,1
3,53,Private,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,1
4,28,Private,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,1
5,37,Private,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,1
6,49,Private,9th,5,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0,0,16,Jamaica,1
7,52,Self-emp-not-inc,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,1
8,31,Private,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,1
9,42,Private,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178,0,40,United-States,1
10,37,Private,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,80,United-States,1
11,30,State-gov,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,40,India,1
12,23,Private,Bachelors,13,Never-married,Adm-clerical,Own-child,White,Female,0,0,30,United-States,1
13,32,Private,Assoc-acdm,12,Never-married,Sales,Not-in-family,Black,Male,0,0,50,United-States,1
14,40,Private,Assoc-voc,11,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,0,0,40,?,1
15,34,Private,7th-8th,4,Married-civ-spouse,Transport-moving,Husband,Amer-Indian-Eskimo,Male,0,0,45,Mexico,1
16,25,Self-emp-not-inc,HS-grad,9,Never-married,Farming-fishing,Own-child,White,Male,0,0,35,United-States,1
17,32,Private,HS-grad,9,Never-married,Machine-op-inspct,Unmarried,White,Male,0,0,40,United-States,1
18,38,Private,11th,7,Married-civ-spouse,Sales,Husband,White,Male,0,0,50,United-States,1
19,43,Self-emp-not-inc,Masters,14,Divorced,Exec-managerial,Unmarried,White,Female,0,0,45,United-States,1
20,40,Private,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,1
21,54,Private,HS-grad,9,Separated,Other-service,Unmarried,Black,Female,0,0,20,United-States,1
22,35,Federal-gov,9th,5,Married-civ-spouse,Farming-fishing,Husband,Black,Male,0,0,40,United-States,1
23,43,Private,11th,7,Married-civ-spouse,Transport-moving,Husband,White,Male,0,2042,40,United-States,1
24,59,Private,HS-grad,9,Divorced,Tech-support,Unmarried,White,Female,0,0,40,United-States,1
25,56,Local-gov,Bachelors,13,Married-civ-spouse,Tech-support,Husband,White,Male,0,0,40,United-States,1
26,19,Private,HS-grad,9,Never-married,Craft-repair,Own-child,White,Male,0,0,40,United-States,1
27,54,?,Some-college,10,Married-civ-spouse,?,Husband,Asian-Pac-Islander,Male,0,0,60,South,1
28,39,Private,HS-grad,9,Divorced,Exec-managerial,Not-in-family,White,Male,0,0,80,United-States,1
29,49,Private,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32531,30,?,Bachelors,13,Never-married,?,Not-in-family,Asian-Pac-Islander,Female,0,0,99,United-States,1
32532,34,Private,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,1
32533,54,Private,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,Asian-Pac-Islander,Male,0,0,50,Japan,1
32534,37,Private,Some-college,10,Divorced,Adm-clerical,Unmarried,White,Female,0,0,39,United-States,1
32535,22,Private,12th,8,Never-married,Protective-serv,Own-child,Black,Male,0,0,35,United-States,1
32536,34,Private,Bachelors,13,Never-married,Exec-managerial,Not-in-family,White,Female,0,0,55,United-States,1
32537,30,Private,HS-grad,9,Never-married,Craft-repair,Not-in-family,Black,Male,0,0,46,United-States,1
32538,38,Private,Bachelors,13,Divorced,Prof-specialty,Unmarried,Black,Female,15020,0,45,United-States,1
32539,71,?,Doctorate,16,Married-civ-spouse,?,Husband,White,Male,0,0,10,United-States,1
32540,45,State-gov,HS-grad,9,Separated,Adm-clerical,Own-child,White,Female,0,0,40,United-States,1
32541,41,?,HS-grad,9,Separated,?,Not-in-family,Black,Female,0,0,32,United-States,1
32542,72,?,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,0,0,25,United-States,1
32543,45,Local-gov,Assoc-acdm,12,Divorced,Prof-specialty,Unmarried,White,Female,0,0,48,United-States,1
32544,31,Private,Masters,14,Divorced,Other-service,Not-in-family,Other,Female,0,0,30,United-States,1
32545,39,Local-gov,Assoc-acdm,12,Married-civ-spouse,Adm-clerical,Wife,White,Female,0,0,20,United-States,1
32546,37,Private,Assoc-acdm,12,Divorced,Tech-support,Not-in-family,White,Female,0,0,40,United-States,1
32547,43,Private,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,Mexico,1
32548,65,Self-emp-not-inc,Prof-school,15,Never-married,Prof-specialty,Not-in-family,White,Male,1086,0,60,United-States,1
32549,43,State-gov,Some-college,10,Divorced,Adm-clerical,Other-relative,White,Female,0,0,40,United-States,1
32550,43,Self-emp-not-inc,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,50,United-States,1
32551,32,Private,10th,6,Married-civ-spouse,Handlers-cleaners,Husband,Amer-Indian-Eskimo,Male,0,0,40,United-States,1
32552,43,Private,Assoc-voc,11,Married-civ-spouse,Sales,Husband,White,Male,0,0,45,United-States,1
32553,32,Private,Masters,14,Never-married,Tech-support,Not-in-family,Asian-Pac-Islander,Male,0,0,11,Taiwan,1
32554,53,Private,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,1
32555,22,Private,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,1
32556,27,Private,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,1
32557,40,Private,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,1
32558,58,Private,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,1
32559,22,Private,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,1
32560,52,Self-emp-inc,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,1

In [52]:
my_scaled_data = pd.DataFrame(my_data)

In [53]:
type(my_scaled_data)

pandas.core.frame.DataFrame

In [54]:
x_data = my_scaled_data.drop(['income_bracket'], axis =1)

In [55]:
y_true = my_scaled_data['income_bracket']

### Perform a Train Test Split on the Data

In [56]:
from sklearn.model_selection import train_test_split

In [57]:
x_test, x_eval, y_test, y_eval = train_test_split(x_data, y_true,
                                                 test_size=0.3, 
                                                  random_state=101)

In [58]:
x_test.shape
x_eval.shape

(9769, 13)

### Create the Feature Columns for tf.esitmator

** Take note of categorical vs continuous values! **

In [59]:
my_scaled_data.columns

Index(['age', 'workclass', 'education', 'education_num', 'marital_status',
       'occupation', 'relationship', 'race', 'gender', 'capital_gain',
       'capital_loss', 'hours_per_week', 'native_country', 'income_bracket'],
      dtype='object')

** Import Tensorflow **

In [60]:
# imported above

** Create the tf.feature_columns for the categorical values. Use vocabulary lists or just use hash buckets. **

In [61]:
gender = tf.feature_column.categorical_column_with_vocabulary_list("gender", ["Female", "Male"])
occupation = tf.feature_column.categorical_column_with_hash_bucket("occupation", hash_bucket_size=1000)
marital_status = tf.feature_column.categorical_column_with_hash_bucket("marital_status", hash_bucket_size=1000)
relationship = tf.feature_column.categorical_column_with_hash_bucket("relationship", hash_bucket_size=1000)
education = tf.feature_column.categorical_column_with_hash_bucket("education", hash_bucket_size=1000)
workclass = tf.feature_column.categorical_column_with_hash_bucket("workclass", hash_bucket_size=1000)
native_country = tf.feature_column.categorical_column_with_hash_bucket("native_country", hash_bucket_size=1000)

** Create the continuous feature_columns for the continuous values using numeric_column **

In [62]:
my_scaled_data.columns

Index(['age', 'workclass', 'education', 'education_num', 'marital_status',
       'occupation', 'relationship', 'race', 'gender', 'capital_gain',
       'capital_loss', 'hours_per_week', 'native_country', 'income_bracket'],
      dtype='object')

In [63]:
age = tf.feature_column.numeric_column("age")
education_num = tf.feature_column.numeric_column("education_num")
capital_gain = tf.feature_column.numeric_column("capital_gain")
capital_loss = tf.feature_column.numeric_column("capital_loss")
hours_per_week = tf.feature_column.numeric_column("hours_per_week")

** Put all these variables into a single list with the variable name feat_cols **

In [64]:
feat_cols = [gender,occupation,marital_status,relationship,education,workclass,native_country,
            age,education_num,capital_gain,capital_loss,hours_per_week]

### Create Input Function

** Batch_size is up to you. But do make sure to shuffle!**

In [65]:
input_func = tf.estimator.inputs.pandas_input_fn(x=x_test, y=y_test,batch_size=10,
                                          shuffle=True, num_epochs = 1000)

#### Create your model with tf.estimator

**Create a LinearClassifier.(If you want to use a DNNClassifier, keep in mind you'll need to create embedded columns out of the cateogrical feature that use strings, check out the previous lecture on this for more info.)**

In [66]:
my_lin_model = tf.estimator.LinearClassifier(feature_columns=feat_cols)

INFO:tensorflow:Using default config.
WARNING:tensorflow:Using temporary folder as model directory: /var/folders/qy/8gpp2k295j980h0fyf_7b4h80000gp/T/tmpocq3p2ym
INFO:tensorflow:Using config: {'_model_dir': '/var/folders/qy/8gpp2k295j980h0fyf_7b4h80000gp/T/tmpocq3p2ym', '_tf_random_seed': 1, '_save_summary_steps': 100, '_save_checkpoints_secs': 600, '_save_checkpoints_steps': None, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100}

** Train your model on the data, for at least 5000 steps. **

In [67]:
my_lin_model.train(input_fn= input_func, steps = 10000)

INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Saving checkpoints for 1 into /var/folders/qy/8gpp2k295j980h0fyf_7b4h80000gp/T/tmpocq3p2ym/model.ckpt.
INFO:tensorflow:loss = 6.931472, step = 1
INFO:tensorflow:global_step/sec: 201.538
INFO:tensorflow:loss = 1.4869439e-05, step = 101 (0.502 sec)
INFO:tensorflow:global_step/sec: 316.699
INFO:tensorflow:loss = 2.9735753e-07, step = 201 (0.318 sec)
INFO:tensorflow:global_step/sec: 294.613
INFO:tensorflow:loss = 9.367814e-06, step = 301 (0.333 sec)
INFO:tensorflow:global_step/sec: 294.8
INFO:tensorflow:loss = 7.6209626e-06, step = 401 (0.339 sec)
INFO:tensorflow:global_step/sec: 333.606
INFO:tensorflow:loss = 2.5308887e-06, step = 501 (0.304 sec)
INFO:tensorflow:global_step/sec: 187.994
INFO:tensorflow:loss = 3.7510923e-05, step = 601 (0.536 sec)
INFO:tensorflow:global_step/sec: 322.772
INFO:tensorflow:loss = 5.6448175e-07, step = 701 (0.308 sec)
INFO:tensorflow:global_step/sec: 236.637
INFO:tensorflow:loss = 5.073166e-07, step = 801 (0.425 sec)
INFO:tensorflow:global_step/sec: 295.496
INFO:tensorflow:loss = 0.00015069218, step = 901 (0.338 sec)
INFO:tensorflow:global_step/sec: 213.65
INFO:tensorflow:loss = 1.2242258e-06, step = 1001 (0.463 sec)
INFO:tensorflow:global_step/sec: 251.577
INFO:tensorflow:loss = 2.1604004e-07, step = 1101 (0.402 sec)
INFO:tensorflow:global_step/sec: 203.462
INFO:tensorflow:loss = 9.0286625e-07, step = 1201 (0.489 sec)
INFO:tensorflow:global_step/sec: 298.17
INFO:tensorflow:loss = 3.6029615e-08, step = 1301 (0.335 sec)
INFO:tensorflow:global_step/sec: 215.873
INFO:tensorflow:loss = 2.4463883e-05, step = 1401 (0.463 sec)
INFO:tensorflow:global_step/sec: 218.509
INFO:tensorflow:loss = 6.8550196e-07, step = 1501 (0.456 sec)
INFO:tensorflow:global_step/sec: 309.034
INFO:tensorflow:loss = 9.4607145e-07, step = 1601 (0.332 sec)
INFO:tensorflow:global_step/sec: 251.642
INFO:tensorflow:loss = 0.00018495994, step = 1701 (0.393 sec)
INFO:tensorflow:global_step/sec: 298.113
INFO:tensorflow:loss = 3.0379364e-05, step = 1801 (0.336 sec)
INFO:tensorflow:global_step/sec: 303.633
INFO:tensorflow:loss = 4.076638e-08, step = 1901 (0.331 sec)
INFO:tensorflow:global_step/sec: 316.85
INFO:tensorflow:loss = 4.8829834e-06, step = 2001 (0.314 sec)
INFO:tensorflow:global_step/sec: 200.183
INFO:tensorflow:loss = 0.000116098934, step = 2101 (0.500 sec)
INFO:tensorflow:global_step/sec: 308.758
INFO:tensorflow:loss = 3.4425368e-05, step = 2201 (0.322 sec)
INFO:tensorflow:global_step/sec: 213.31
INFO:tensorflow:loss = 3.6520873e-05, step = 2301 (0.473 sec)
INFO:tensorflow:global_step/sec: 236.217
INFO:tensorflow:loss = 4.9318014e-06, step = 2401 (0.421 sec)
INFO:tensorflow:global_step/sec: 317.569
INFO:tensorflow:loss = 6.5530753e-07, step = 2501 (0.315 sec)
INFO:tensorflow:global_step/sec: 302.727
INFO:tensorflow:loss = 3.8116423e-07, step = 2601 (0.331 sec)
INFO:tensorflow:global_step/sec: 304.074
INFO:tensorflow:loss = 4.1334046e-05, step = 2701 (0.329 sec)
INFO:tensorflow:global_step/sec: 311.576
INFO:tensorflow:loss = 2.2386312e-06, step = 2801 (0.316 sec)
INFO:tensorflow:global_step/sec: 273.414
INFO:tensorflow:loss = 1.559127e-06, step = 2901 (0.366 sec)
INFO:tensorflow:global_step/sec: 296.037
INFO:tensorflow:loss = 4.9826177e-08, step = 3001 (0.336 sec)
INFO:tensorflow:global_step/sec: 195.892
INFO:tensorflow:loss = 8.055125e-06, step = 3101 (0.522 sec)
INFO:tensorflow:global_step/sec: 304.919
INFO:tensorflow:loss = 1.5236047e-07, step = 3201 (0.320 sec)
INFO:tensorflow:global_step/sec: 247.011
INFO:tensorflow:loss = 0.00013122511, step = 3301 (0.409 sec)
INFO:tensorflow:global_step/sec: 302.719
INFO:tensorflow:loss = 9.345369e-06, step = 3401 (0.324 sec)
INFO:tensorflow:global_step/sec: 309.28
INFO:tensorflow:loss = 1.490014e-07, step = 3501 (0.325 sec)
INFO:tensorflow:global_step/sec: 315.805
INFO:tensorflow:loss = 3.1171527e-05, step = 3601 (0.319 sec)
INFO:tensorflow:global_step/sec: 316.987
INFO:tensorflow:loss = 6.247652e-05, step = 3701 (0.315 sec)
INFO:tensorflow:global_step/sec: 312.377
INFO:tensorflow:loss = 4.350554e-06, step = 3801 (0.319 sec)
INFO:tensorflow:global_step/sec: 271.631
INFO:tensorflow:loss = 3.3984055e-05, step = 3901 (0.371 sec)
INFO:tensorflow:global_step/sec: 314.317
INFO:tensorflow:loss = 1.14889886e-07, step = 4001 (0.317 sec)
INFO:tensorflow:global_step/sec: 303.697
INFO:tensorflow:loss = 9.825794e-06, step = 4101 (0.329 sec)
INFO:tensorflow:global_step/sec: 207.305
INFO:tensorflow:loss = 2.379624e-06, step = 4201 (0.483 sec)
INFO:tensorflow:global_step/sec: 303.775
INFO:tensorflow:loss = 2.5740517e-05, step = 4301 (0.324 sec)
INFO:tensorflow:global_step/sec: 179.466
INFO:tensorflow:loss = 1.214817e-07, step = 4401 (0.562 sec)
INFO:tensorflow:global_step/sec: 250.131
INFO:tensorflow:loss = 4.5524917e-05, step = 4501 (0.399 sec)
INFO:tensorflow:global_step/sec: 242.529
INFO:tensorflow:loss = 2.962042e-05, step = 4601 (0.415 sec)
INFO:tensorflow:global_step/sec: 178.231
INFO:tensorflow:loss = 3.531025e-06, step = 4701 (0.558 sec)
INFO:tensorflow:global_step/sec: 182.341
INFO:tensorflow:loss = 1.0008645e-06, step = 4801 (0.544 sec)
INFO:tensorflow:global_step/sec: 198.991
INFO:tensorflow:loss = 1.2269921e-05, step = 4901 (0.513 sec)
INFO:tensorflow:global_step/sec: 152.928
INFO:tensorflow:loss = 4.086207e-06, step = 5001 (0.642 sec)
INFO:tensorflow:global_step/sec: 160.848
INFO:tensorflow:loss = 2.4691192e-06, step = 5101 (0.625 sec)
INFO:tensorflow:global_step/sec: 201.992
INFO:tensorflow:loss = 2.2791141e-07, step = 5201 (0.492 sec)
INFO:tensorflow:global_step/sec: 218.124
INFO:tensorflow:loss = 0.00015266522, step = 5301 (0.464 sec)
INFO:tensorflow:global_step/sec: 200.944
INFO:tensorflow:loss = 0.00026945057, step = 5401 (0.495 sec)
INFO:tensorflow:global_step/sec: 324.553
INFO:tensorflow:loss = 8.242404e-07, step = 5501 (0.308 sec)
INFO:tensorflow:global_step/sec: 224.869
INFO:tensorflow:loss = 1.8953676e-07, step = 5601 (0.447 sec)
INFO:tensorflow:global_step/sec: 320.698
INFO:tensorflow:loss = 7.780366e-08, step = 5701 (0.311 sec)
INFO:tensorflow:global_step/sec: 264.414
INFO:tensorflow:loss = 4.4757646e-05, step = 5801 (0.380 sec)
INFO:tensorflow:global_step/sec: 236.583
INFO:tensorflow:loss = 1.3267546e-05, step = 5901 (0.424 sec)
INFO:tensorflow:global_step/sec: 205.471
INFO:tensorflow:loss = 2.4163614e-07, step = 6001 (0.485 sec)
INFO:tensorflow:global_step/sec: 224.529
INFO:tensorflow:loss = 1.4777851e-05, step = 6101 (0.450 sec)
INFO:tensorflow:global_step/sec: 204.513
INFO:tensorflow:loss = 2.6181996e-07, step = 6201 (0.478 sec)
INFO:tensorflow:global_step/sec: 130.512
INFO:tensorflow:loss = 5.312284e-07, step = 6301 (0.772 sec)
INFO:tensorflow:global_step/sec: 160.273
INFO:tensorflow:loss = 1.7449926e-05, step = 6401 (0.623 sec)
INFO:tensorflow:global_step/sec: 258.341
INFO:tensorflow:loss = 5.1136e-06, step = 6501 (0.389 sec)
INFO:tensorflow:global_step/sec: 263.856
INFO:tensorflow:loss = 3.9463535e-05, step = 6601 (0.380 sec)
INFO:tensorflow:global_step/sec: 321.391
INFO:tensorflow:loss = 4.114404e-07, step = 6701 (0.317 sec)
INFO:tensorflow:global_step/sec: 230.197
INFO:tensorflow:loss = 0.00011649194, step = 6801 (0.425 sec)
INFO:tensorflow:global_step/sec: 332.651
INFO:tensorflow:loss = 2.6287323e-06, step = 6901 (0.304 sec)
INFO:tensorflow:global_step/sec: 224.227
INFO:tensorflow:loss = 2.8234925e-05, step = 7001 (0.444 sec)
INFO:tensorflow:global_step/sec: 145.927
INFO:tensorflow:loss = 1.0740515e-06, step = 7101 (0.688 sec)
INFO:tensorflow:global_step/sec: 159.997
INFO:tensorflow:loss = 1.05330855e-07, step = 7201 (0.623 sec)
INFO:tensorflow:global_step/sec: 304.084
INFO:tensorflow:loss = 0.0002540233, step = 7301 (0.328 sec)
INFO:tensorflow:global_step/sec: 231.081
INFO:tensorflow:loss = 3.208253e-07, step = 7401 (0.431 sec)
INFO:tensorflow:global_step/sec: 294.208
INFO:tensorflow:loss = 1.4845962e-06, step = 7501 (0.343 sec)
INFO:tensorflow:global_step/sec: 189.813
INFO:tensorflow:loss = 8.020917e-05, step = 7601 (0.526 sec)
INFO:tensorflow:global_step/sec: 200.712
INFO:tensorflow:loss = 1.2955379e-06, step = 7701 (0.499 sec)
INFO:tensorflow:global_step/sec: 282.833
INFO:tensorflow:loss = 1.3877253e-06, step = 7801 (0.353 sec)
INFO:tensorflow:global_step/sec: 212.875
INFO:tensorflow:loss = 7.603613e-08, step = 7901 (0.469 sec)
INFO:tensorflow:global_step/sec: 322.146
INFO:tensorflow:loss = 2.2201309e-07, step = 8001 (0.312 sec)
INFO:tensorflow:global_step/sec: 225.187
INFO:tensorflow:loss = 6.7137614e-07, step = 8101 (0.443 sec)
INFO:tensorflow:global_step/sec: 243.921
INFO:tensorflow:loss = 3.7580378e-07, step = 8201 (0.411 sec)
INFO:tensorflow:global_step/sec: 269.929
INFO:tensorflow:loss = 2.3896643e-08, step = 8301 (0.371 sec)
INFO:tensorflow:global_step/sec: 348.067
INFO:tensorflow:loss = 2.1881256e-08, step = 8401 (0.288 sec)
INFO:tensorflow:global_step/sec: 340.348
INFO:tensorflow:loss = 2.6331456e-05, step = 8501 (0.293 sec)
INFO:tensorflow:global_step/sec: 333.441
INFO:tensorflow:loss = 2.3096842e-07, step = 8601 (0.297 sec)
INFO:tensorflow:global_step/sec: 335.376
INFO:tensorflow:loss = 7.6160336e-06, step = 8701 (0.295 sec)
INFO:tensorflow:global_step/sec: 300.124
INFO:tensorflow:loss = 4.578778e-07, step = 8801 (0.338 sec)
INFO:tensorflow:global_step/sec: 257.094
INFO:tensorflow:loss = 5.885229e-07, step = 8901 (0.383 sec)
INFO:tensorflow:global_step/sec: 265.616
INFO:tensorflow:loss = 2.1001395e-07, step = 9001 (0.376 sec)
INFO:tensorflow:global_step/sec: 263.495
INFO:tensorflow:loss = 0.00088419876, step = 9101 (0.386 sec)
INFO:tensorflow:global_step/sec: 212.515
INFO:tensorflow:loss = 2.2457039e-07, step = 9201 (0.471 sec)
INFO:tensorflow:global_step/sec: 197.129
INFO:tensorflow:loss = 3.254717e-05, step = 9301 (0.506 sec)
INFO:tensorflow:global_step/sec: 323.865
INFO:tensorflow:loss = 0.0005905583, step = 9401 (0.313 sec)
INFO:tensorflow:global_step/sec: 223.6
INFO:tensorflow:loss = 0.00021891441, step = 9501 (0.441 sec)
INFO:tensorflow:global_step/sec: 226.948
INFO:tensorflow:loss = 1.03133694e-07, step = 9601 (0.437 sec)
INFO:tensorflow:global_step/sec: 242.157
INFO:tensorflow:loss = 6.3200923e-07, step = 9701 (0.413 sec)
INFO:tensorflow:global_step/sec: 260.941
INFO:tensorflow:loss = 5.1182415e-06, step = 9801 (0.383 sec)
INFO:tensorflow:global_step/sec: 254.458
INFO:tensorflow:loss = 0.0001626181, step = 9901 (0.393 sec)
INFO:tensorflow:Saving checkpoints for 10000 into /var/folders/qy/8gpp2k295j980h0fyf_7b4h80000gp/T/tmpocq3p2ym/model.ckpt.
INFO:tensorflow:Loss for final step: 4.8488355e-06.

### Evaluation

** Create a prediction input function. Remember to only supprt X_test data and keep shuffle=False. **

In [68]:
pred_func = tf.estimator.inputs.pandas_input_fn(x=x_test, batch_size=10, 
                                                shuffle= False,
                                               num_epochs= 1000)

** Use model.predict() and pass in your input function. This will produce a generator of predictions, which you can then transform into a list, with list() **

In [69]:
my_lin_model.predict(input_fn = pred_func)

** Each item in your list will look like this: **

In [ ]:
my_list_pred = list(my_lin_model.predict(input_fn = pred_func))

INFO:tensorflow:Restoring parameters from /var/folders/qy/8gpp2k295j980h0fyf_7b4h80000gp/T/tmpocq3p2ym/model.ckpt-10000

In [ ]:
my_list_pred

** Create a list of only the class_ids key values from the prediction list of dictionaries, these are the predictions you will use to compare against the real y_test values. **

[0, 0, 0, 0, 1, 0, 0, 0, 0, 0]

** Import classification_report from sklearn.metrics and then see if you can figure out how to use it to easily get a full report of your model's performance on the test data. **

             precision    recall  f1-score   support

          0       0.88      0.92      0.90      7436
          1       0.70      0.59      0.64      2333

avg / total       0.84      0.84      0.84      9769

# Great Job!